### ISSUE TITLE
any plan to update to 6.12?

### ISSUE THREAD

**Issue by MarisaKirisame** [samwaxman/MysteryLanguages611#1]
6.12 is out and it will be nice if it could be recompiled again.

**Comment by samwaxman** [comment]
The Mystery Languages are in the process of being updated and added onto, so I'm imagining we'll do a recompile right before fall semester starts. If any of the departments using these have updated to 6.12, then we'd do a 6.12 build.

If you just want the current Mystery Languages, but for 6.12, I didn't have any plans of doing that, but it wouldn't be too hard to do, and I could get to it within the next few days.

What are you using the Mystery Languages for? I wasn't aware anyone was using these save for two colleges.

**Comment by MarisaKirisame** [comment]
I am just having fun with it, not any college stuff.

I got racket 6.11 compiled, and it work, so I guess I should close this.
